spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/discovery}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    properties:
        hibernate:
            format_sql: ${JPA_HIBERNATE_FORMAT_SQL:true}
            show_sql: ${JPA_HIBERNATE_SHOW_SQL:true}

seeder:
  enabled: false
  author-count: 10
  book-for-each-author: 5
